<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
    <div class="row" id="MainCSS">
        <div class="col-1"></div>
        <div class="col-8">
            <div class="space" />
            <h2>修改密码</h2>
            <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="80px"
                size="default" @submit.prevent>
                <el-form-item label="原密码" prop="oldpassword" class="required">
                    <el-input v-model="formData.oldpassword" type="password" :show-password="true" clearable></el-input>
                </el-form-item>
                <el-form-item label="新密码" prop="newpassword" class="required">
                    <el-input v-model="formData.newpassword" type="password" :show-password="true" clearable></el-input>
                </el-form-item>
                <el-form-item label="确认密码" prop="curpassword" class="required">
                    <el-input v-model="formData.curpassword" type="password" :show-password="true" clearable></el-input>
                </el-form-item>
            </el-form>
            <el-button type="primary" @click="this.submitForm()">确认更改</el-button>
            <div class="space"/>
        </div>
    </div>
</template>

<script>
import { ref, reactive } from 'vue';
import { ElMessage } from 'element-plus';
// import {GetUid} from "@/module/User/UserFunctionLib";

export default {
    components: {},
    props: {},
    name: 'ChangeUserPassword',
    data() {
        return {
            uid: '',
            formData: {
                oldpassword: "",
                newpassword: "",
                curpassword: "",
            },
            rules: {
                oldpassword: [{
                    required: true,
                    message: '字段值不可为空',
                }],
                newpassword: [{
                    required: true,
                    message: '字段值不可为空',
                }, {
                    pattern: /^[A-Za-z0-9]+$/,
                    trigger: ['blur', 'change'],
                    message: ''
                }],
                curpassword: [{
                    required: true,
                    message: '字段值不可为空',
                }, {
                    pattern: /^[A-Za-z0-9]+$/,
                    trigger: ['blur', 'change'],
                    message: ''
                }],
            },
        }
    },
    computed: {},
    watch: {},
    created() {
        this.$data.uid = this.$route.query.uid;
    },
    mounted() {
    },
    methods: {
        submitForm() {
            this.$refs['vForm'].validate(valid => {
                if (!valid) {
                    ElMessage.error("请输入完整数据");
                    return;
                }
                // alert((this.$data.formData.curpassword) + ' ' + (this.$data.formData.newpassword));
                if (this.$data.formData.newpassword !== this.$data.formData.curpassword) {
                    ElMessage.error("两次输入的密码不一致！");
                    return;
                }
                let data = new FormData();
                data.append('oldpassword', this.$data.formData.oldpassword);
                data.append('newpassword', this.$data.formData.newpassword);
                this.axios.post('/AppUser/api/ChangeUserPassword/' + this.$data.uid, data).then((res) => {
                    if (res.data.code === 'ok') {
                        //
                        // alert("修改成功！");
                        this.$message({
                            message: '修改成功！',
                            type: 'success',
                            center: true,
                        });
                        window.location.href = '/login/';
                    } else {
                        ElMessage.error(res.data.message);
                    }
                })
                // alert( JSON.stringify(formData) );
            }).catch(error => {
                // Form Validation failed
                ElMessage.error(error);
                //TODO: 提交表单
            })
        },
        resetForm() {
            this.$refs['vForm'].resetFields()
        }
    }
}

</script>

<style lang="scss">
.el-input-number.full-width-input,
.el-cascader.full-width-input {
    width: 100% !important;
}

.el-form-item--medium {
    .el-radio {
        line-height: 36px !important;
    }

    .el-rate {
        margin-top: 8px;
    }
}

.el-form-item--small {
    .el-radio {
        line-height: 32px !important;
    }

    .el-rate {
        margin-top: 6px;
    }
}

.el-form-item--mini {
    .el-radio {
        line-height: 28px !important;
    }

    .el-rate {
        margin-top: 4px;
    }
}

.clear-fix:before,
.clear-fix:after {
    display: table;
    content: "";
}

.clear-fix:after {
    clear: both;
}

.float-right {
    float: right;
}
</style>

<style lang="scss" scoped>
div.table-container {
    table.table-layout {
        width: 100%;
        table-layout: fixed;
        border-collapse: collapse;

        td.table-cell {
            display: table-cell;
            height: 36px;
            border: 1px solid #e1e2e3;
        }
    }
}

div.tab-container {}

.label-left-align ::v-deep .el-form-item__label {
    text-align: left;
}

.label-center-align ::v-deep .el-form-item__label {
    text-align: center;
}

.label-right-align ::v-deep .el-form-item__label {
    text-align: right;
}

.custom-label {}

.static-content-item {
    min-height: 20px;
    display: flex;
    align-items: center;

    ::v-deep .el-divider--horizontal {
        margin: 0;
    }
}
</style>