<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
    <div class="row" id="MainCSS">
        <div class="col-1"></div>
        <div class="col-8">
            <div class="space"/>
            <h2>修改个人信息</h2>
            <div class="space"/>
            <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="80px"
                size="default" @submit.prevent>
                <el-form-item label="用户名" prop="openname" class="required">
                    <el-input v-model="formData.openname" type="text" clearable></el-input>
                </el-form-item>
                <el-form-item label="用户简介" prop="about">
                    <el-input type="textarea" v-model="formData.about" rows="3"></el-input>
                </el-form-item>
            </el-form>
            <el-button type="primary" @click="this.submitForm()">确认更改</el-button>
            <div class="space"/>
        </div>
    </div>
</template>

<script>
import { ref, reactive } from 'vue';
import { ElMessage } from 'element-plus';
// import {GetUid} from "@/module/User/UserFunctionLib";
export default {
    components: {},
    props: {},
    data() {
        return {
            uid: '',
            formData: {
                openname: "",
                about: "",
            },
            rules: {
                openname: [{
                    required: true,
                    message: '字段值不可为空',
                }],
                about: [{
                    required: true,
                    message: '字段值不可为空',
                }],
            },
        }
    },
    computed: {},
    watch: {},
    created() {
        let uid = this.$route.query.uid;
        if (uid == null || uid == '') {
            window.location.href = '/NotFoundPage';
            return;
        }
        this.axios.get('/AppUser/api/GetUserInformation/' + uid).then((res) => {
            // alert(res.data.code);
            if (res.data.code === "error") {
                //跳转到用户404界面
                // alert('b');
                window.location.href = '/NotFoundPage';
            } else {
                //
                // alert('c');
                let userData = res.data.result[0].fields;
                this.$data.formData.openname = userData.open_name;
                this.$data.formData.about = userData.about;
                this.$data.uid = userData.uid;
                // alert(res.data.result[0].fields);
            }
        })
    },
    mounted() {
    },
    methods: {
        submitForm() {
            this.$refs['vForm'].validate(valid => {
                if (!valid) {
                    ElMessage.error("请输入完整数据");
                    return;
                }
                let data = new FormData();
                data.append('openname', this.$data.formData.openname);
                data.append('about', this.$data.formData.about);
                this.axios.post('/AppUser/api/ChangeUserInfo/' + this.$data.uid, data).then((res) => {
                    if (res.data.code === 'ok') {
                        //
                        this.$message({
                            message: '修改成功！',
                            type: 'success',
                            center: true,
                        })
                    } else {
                        ElMessage.error(res.data.message);
                    }
                })
            })
        },
        resetForm() {
            this.$refs['vForm'].resetFields()
        }
    }
}

</script>

<style lang="scss">
#MainCSS{
    background-color: white; 
    border-radius: 8px 8px 8px 8px;
}
.space{
    width: 2em;
    height: 1em;
}

.el-input-number.full-width-input,
.el-cascader.full-width-input {
    width: 100% !important;
}

.el-form-item--medium {
    .el-radio {
        line-height: 36px !important;
    }

    .el-rate {
        margin-top: 8px;
    }
}

.el-form-item--small {
    .el-radio {
        line-height: 32px !important;
    }

    .el-rate {
        margin-top: 6px;
    }
}

.el-form-item--mini {
    .el-radio {
        line-height: 28px !important;
    }

    .el-rate {
        margin-top: 4px;
    }
}

.clear-fix:before,
.clear-fix:after {
    display: table;
    content: "";
}

.clear-fix:after {
    clear: both;
}

.float-right {
    float: right;
}
</style>

<style lang="scss" scoped>
div.table-container {
    table.table-layout {
        width: 100%;
        table-layout: fixed;
        border-collapse: collapse;

        td.table-cell {
            display: table-cell;
            height: 36px;
            border: 1px solid #e1e2e3;
        }
    }
}

div.tab-container {}

.label-left-align ::v-deep .el-form-item__label {
    text-align: left;
}

.label-center-align ::v-deep .el-form-item__label {
    text-align: center;
}

.label-right-align ::v-deep .el-form-item__label {
    text-align: right;
}

.custom-label {}

.static-content-item {
    min-height: 20px;
    display: flex;
    align-items: center;

    ::v-deep .el-divider--horizontal {
        margin: 0;
    }
}
</style>