<!--
Codes Generated By VForm:
https://www.vform666.com
-->

<template>
    <h3>发表评论</h3>
    <div class="space"></div>
    <el-form :model="formData" ref="vForm" :rules="rules" label-position="left" label-width="80px"
             size="default" @submit.prevent>
        <el-form-item label="评论" prop="userComment" class="required">
            <el-input type="textarea" v-model="formData.userComment" rows="3"></el-input>
        </el-form-item>
        <el-form-item label="评分" prop="rate" class="required">
            <el-rate v-model="formData.rate" allow-half></el-rate>
        </el-form-item>
        <el-form-item label="公开评论" prop="IsPublic">
            <el-switch v-model="formData.IsPublic"></el-switch>
        </el-form-item>
        <div class="static-content-item">
            <el-button type="primary" @click="submitForm()">发布评论</el-button>
        </div>
    </el-form>

</template>

<script>
import {ElMessage} from "element-plus";
// import {GetMediaId} from "@/module/Comment/CommentFunctionLib";

export default {
    name: 'UserComment',
    components: {},
    props: {},
    data() {
        return {
            mediaId: 0,
            formData: {
                userComment: "",
                rate: 0,
                IsPublic: true,
            },
            rules: {
                userComment: [{
                    required: true,
                    message: '字段值不可为空',
                }],
                rate: [{
                    required: true,
                    message: '字段值不可为空',
                }],
            },
        }
    },
    computed: {},
    watch: {},
    created() {
        this.$data.mediaId = this.$route.query.media_id;//GetMediaId();
    },
    mounted() {
    },
    methods: {
        submitForm() {
            this.$refs['vForm'].validate(valid => {
                if (!valid) {
                    ElMessage.error('请输入完整数据');
                    return;
                }
                let data = new FormData();
                data.append('Comment', this.$data.formData.userComment);
                data.append('Rating', this.$data.formData.rate);
                data.append('IsPublic', this.$data.formData.IsPublic);
                data.append('mediaId', this.$data.mediaId);
                // alert(111);
                this.axios.post('/Comment/api/PostComment/', data).then((res) => {
                    //
                    if (res.data.code === 'ok') {
                        //
                        this.$message({
                            message: res.data.message,
                            type: 'success',
                            center: true,
                        })
                        location.reload();
                        return;
                    } else {
                        // 输出错误信息
                        ElMessage.error(res.data.message);
                        return;
                    }
                })
            })
        },
        resetForm() {
            this.$refs['vForm'].resetFields()
        }
    }
}

</script>

<style lang="scss">
.el-input-number.full-width-input,
.el-cascader.full-width-input {
    width: 100% !important;
}

.el-form-item--medium {
    .el-radio {
        line-height: 36px !important;
    }

    .el-rate {
        margin-top: 8px;
    }
}

.el-form-item--small {
    .el-radio {
        line-height: 32px !important;
    }

    .el-rate {
        margin-top: 6px;
    }
}

.el-form-item--mini {
    .el-radio {
        line-height: 28px !important;
    }

    .el-rate {
        margin-top: 4px;
    }
}

.clear-fix:before,
.clear-fix:after {
    display: table;
    content: "";
}

.clear-fix:after {
    clear: both;
}

.float-right {
    float: right;
}

</style>

<style lang="scss" scoped>
div.table-container {
    table.table-layout {
        width: 100%;
        table-layout: fixed;
        border-collapse: collapse;

        td.table-cell {
            display: table-cell;
            height: 36px;
            border: 1px solid #e1e2e3;
        }
    }
}

div.tab-container {
}

.label-left-align ::v-deep .el-form-item__label {
    text-align: left;
}

.label-center-align ::v-deep .el-form-item__label {
    text-align: center;
}

.label-right-align ::v-deep .el-form-item__label {
    text-align: right;
}

.custom-label {
}

.static-content-item {
    min-height: 20px;
    display: flex;
    align-items: center;

    ::v-deep .el-divider--horizontal {
        margin: 0;
    }
}

</style>