# Generated by Django 4.1.2 on 2022-12-02 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('arealimit', models.IntegerField()),
                ('attention', models.IntegerField()),
                ('bnguimi_id', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('cover', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('danmaku_count', models.IntegerField()),
                ('ep_id', models.IntegerField()),
                ('favorites', models.IntegerField()),
                ('is_finish', models.IntegerField()),
                ('lastupdate', models.IntegerField()),
                ('lastupdate_at', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('new', models.BooleanField()),
                ('play_count', models.IntegerField()),
                ('pub_time', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('season_id', models.IntegerField()),
                ('season_status', models.IntegerField()),
                ('spid', models.IntegerField()),
                ('square_cover', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('viewRank', models.IntegerField()),
                ('weekday', models.IntegerField()),
            ],
        ),
    ]
