# Generated by Django 4.1.2 on 2022-12-02 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0002_alter_anime_arealimit_alter_anime_attention_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='bnguimi_id',
            new_name='banguimi_id',
        ),
    ]
