# Generated by Django 4.1.2 on 2022-12-02 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0004_rename_banguimi_id_anime_bangumi_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='bgmcount',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
