# Generated by Django 4.1.2 on 2022-12-03 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0005_anime_bgmcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='lastupdate_at',
            new_name='first_ep_cover',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='pub_time',
            new_name='index_show',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='square_cover',
            new_name='link',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='arealimit',
            new_name='media_id',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='attention',
            new_name='season_type',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='area',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='bangumi_id',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='bgmcount',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='danmaku_count',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='lastupdate',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='new',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='play_count',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='spid',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='viewRank',
        ),
        migrations.RemoveField(
            model_name='anime',
            name='weekday',
        ),
        migrations.AddField(
            model_name='anime',
            name='order',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='order_type',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='score',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='subTitle',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='title_icon',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
