# Generated by Django 4.1.2 on 2022-12-07 12:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0006_rename_lastupdate_at_anime_first_ep_cover_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sumScore', models.FloatField(default=0)),
                ('cnt', models.FloatField(default=0)),
                ('anime', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='anime', to='Anime.anime')),
            ],
        ),
    ]
