# Generated by Django 4.1.2 on 2022-12-12 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0007_animescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='user_cnt',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='anime',
            name='user_sumScore',
            field=models.IntegerField(default=0),
        ),
    ]
