# Generated by Django 4.1.2 on 2022-12-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0008_anime_user_cnt_anime_user_sumscore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='user_cnt',
        ),
    ]
