# Generated by Django 4.1.2 on 2022-12-14 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0009_remove_anime_user_cnt'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='media_tag',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
