# Generated by Django 4.1.2 on 2022-12-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Anime', '0011_animetag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='user_sumScore',
            field=models.FloatField(default=0),
        ),
    ]
