# Generated by Django 4.1.2 on 2022-12-05 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Anime', '0006_rename_lastupdate_at_anime_first_ep_cover_and_more'),
        ('AppUser', '0002_rename_blogs_user_appuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('CommentID', models.AutoField(primary_key=True, serialize=False)),
                ('test', models.IntegerField(default=0)),
                ('Rating', models.FloatField()),
                ('CommentBody', models.CharField(max_length=200)),
                ('IsPublic', models.BooleanField()),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('CommentAnime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Anime.anime')),
                ('CommentUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='AppUser.appuser')),
            ],
            options={
                'ordering': ('Created',),
            },
        ),
    ]
