# Generated by Django 4.1.2 on 2022-12-09 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0002_remove_comment_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='AnimeCover',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='AnimeTitle',
            field=models.CharField(default='', max_length=50),
        ),
    ]
