# Generated by Django 4.1.2 on 2022-12-09 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0003_comment_animecover_comment_animetitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='mediaId',
            field=models.CharField(default='', max_length=50),
        ),
    ]
