# Generated by Django 4.1.2 on 2022-12-11 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0004_comment_mediaid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='CommentUserName',
            field=models.CharField(default='', max_length=50),
        ),
    ]
