# Generated by Django 4.1.2 on 2022-12-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Comment', '0005_comment_commentusername'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='nasty',
            field=models.IntegerField(default=0),
        ),
    ]
